<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BusinessModels\**" />
    <EmbeddedResource Remove="BusinessModels\**" />
    <None Remove="BusinessModels\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FPT.DestinyMatch.Repository\FPT.DestinyMatch.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseAdmin" Version="3.0.0" />
    <PackageReference Include="FirebaseStorage.net" Version="1.0.3" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
  </ItemGroup>

</Project>
